apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
spec:
  selector:
    matchLabels:
      app: logger
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: logger
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: logger
        image: alicehua11/logger:latest
