apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-deployment
spec:
  selector:
    matchLabels:
      app: detector
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: detector
    spec:
     # hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: detector
        image: alicehua11/detector:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0

