apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: mosquitto
        image: alicehua11/mosquitto:v1
       # ports:
       # - containerPort: 1883
      - name: detector
        image: alicehua11/detector:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
      - name: forwarder
        image: alicehua11/forwarder:latest
      - name: logger
        image: alicehua11/logger:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /home/alicehua/logs
          name: logs
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
      - name: logs
        hostPath:
          path: /home/alicehua/logs 
  
