apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-deployments
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: forwarder
        image: alicehua11/forwarder:latest
      - name: logger
        image: alicehua11/logger:latest
      - name: detector
        image: alicehua11/detector:v1
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0

